# Only override specific settings, let environment handle Immich config
hass_img_path: "C:/Users/manof/Downloads/photos"
update_interval_minutes: 1
log_level: "DEBUG"

# Photo filters - list of filter sets to cycle through
filters:
  - name: "Dogs"
    selector_type: "smart"
    search_query: "Dogs"

  - name: "Photos of the Kids"
    selector_type: "random"
    people: ["Bob Bob", "Bob Bob"]

  - name: "Wedding Photos"
    selector_type: "random"
    people: ["Bob Bob", "Bob Bob"]
    taken_before: "2013-01-01" 
    city: "Atkinson"

  - name: "Vacation Photos"
    selector_type: "smart"
    search_query: "Theme Park"

  - name: "Random Photos From This Year"
    selector_type: "random"
    taken_after: "2024-12-31"
    taken_before: "2025-12-31"